### ISSUE TITLE
Feature Request: 更多随机罐头笑声

### ISSUE THREAD

**Issue by SunsetMkt** [pacexy/canned-laughter#1]
情景喜剧的罐头笑声通常是随机的。

P.S. 真的和Demo中的笑声一起笑了出来。

参考：https://freesound.org/people/Evil_Ear_Recordings/sounds/524775/

**Comment by pacexy** [comment]
很棒的提议，这样确实可以去除一些现有的生硬感。

**Comment by SunsetMkt** [comment]
一些音效示例：

https://freesound.org/people/Evil_Ear_Recordings/sounds/524775/
https://freesound.org/people/HowardV/sounds/581528/
https://freesound.org/people/thanvannispen/sounds/30281/
https://freesound.org/people/aarrnnoo/sounds/520371/
https://freesound.org/people/aarrnnoo/sounds/520366/
https://freesound.org/people/aarrnnoo/sounds/520370/
https://freesound.org/people/aarrnnoo/sounds/520368/
https://freesound.org/people/aarrnnoo/sounds/520375/
https://freesound.org/people/aarrnnoo/sounds/520372/

**Comment by pacexy** [comment]
已更新
